# Generated by Django 4.0.5 on 2022-06-15 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolim', models.CharField(max_length=255, verbose_name="Bo'lim")),
            ],
        ),
        migrations.CreateModel(
            name='Til',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('til', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitob_nomi', models.CharField(max_length=500)),
                ('kitob_muqovasi', models.ImageField(upload_to='images')),
                ('muallif', models.CharField(max_length=200)),
                ('ishlab_chiqaruvchi', models.CharField(max_length=200)),
                ('seriya', models.CharField(max_length=370)),
                ('yil', models.IntegerField()),
                ('bet', models.IntegerField()),
                ('kitob_haqida', models.TextField()),
                ('isbn', models.CharField(max_length=400)),
                ('bolim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.bolim')),
                ('til', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.til')),
            ],
        ),
    ]
