# Generated by Django 4.0.5 on 2022-06-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='bolim',
        ),
        migrations.RemoveField(
            model_name='form',
            name='til',
        ),
        migrations.DeleteModel(
            name='Bolim',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Til',
        ),
    ]
