# Generated by Django 4.0.5 on 2022-06-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
